/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminParentsRouteImport } from './routes/_admin.parents'
import { Route as AdminMessagesRouteImport } from './routes/_admin.messages'
import { Route as AdminLessonsRouteImport } from './routes/_admin.lessons'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminChwsRouteImport } from './routes/_admin.chws'
import { Route as AdminCategoriesRouteImport } from './routes/_admin.categories'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParentsRoute = AdminParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChwsRoute = AdminChwsRouteImport.update({
  id: '/chws',
  path: '/chws',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AdminCategoriesRoute
  '/chws': typeof AdminChwsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/lessons': typeof AdminLessonsRoute
  '/messages': typeof AdminMessagesRoute
  '/parents': typeof AdminParentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AdminCategoriesRoute
  '/chws': typeof AdminChwsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/lessons': typeof AdminLessonsRoute
  '/messages': typeof AdminMessagesRoute
  '/parents': typeof AdminParentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/chws': typeof AdminChwsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/lessons': typeof AdminLessonsRoute
  '/_admin/messages': typeof AdminMessagesRoute
  '/_admin/parents': typeof AdminParentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/chws'
    | '/dashboard'
    | '/lessons'
    | '/messages'
    | '/parents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/chws'
    | '/dashboard'
    | '/lessons'
    | '/messages'
    | '/parents'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/categories'
    | '/_admin/chws'
    | '/_admin/dashboard'
    | '/_admin/lessons'
    | '/_admin/messages'
    | '/_admin/parents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/parents': {
      id: '/_admin/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AdminParentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/messages': {
      id: '/_admin/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/lessons': {
      id: '/_admin/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/chws': {
      id: '/_admin/chws'
      path: '/chws'
      fullPath: '/chws'
      preLoaderRoute: typeof AdminChwsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/categories': {
      id: '/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminChwsRoute: typeof AdminChwsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminParentsRoute: typeof AdminParentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminChwsRoute: AdminChwsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminParentsRoute: AdminParentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
